[package]
name = "markdown_rustified"
version = "0.1.0"
edition = "2021"
authors = ["Koji Onishi <fursich0@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
